import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, Sparkles, User } from "lucide-react";

const MOCK_RESPONSE = `# Digital Persona Report

## Professional Identity
**Name:** Jane Doe  
**Title:** Senior Product Manager at TechCorp  
**Industry:** Enterprise SaaS

---

## Core Competencies
- Product Strategy & Roadmap Development
- Cross-functional Team Leadership
- Data-Driven Decision Making
- Stakeholder Management

## Communication Style
Jane demonstrates a **confident, results-oriented** communication style. Her posts emphasize measurable outcomes and team collaboration. She favors concise, action-oriented language with a professional yet approachable tone.

## Key Themes
1. **Innovation** — Frequently shares insights on emerging tech trends
2. **Leadership** — Advocates for inclusive team cultures
3. **Growth Mindset** — Emphasizes continuous learning and adaptation

## Influence Score
🟢 **High** — Active engagement with a well-curated professional network.

---

*Report generated by Digital Persona Architect*
`;

const PersonaDashboard = () => {
  const [input, setInput] = useState("");
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    if (!input.trim()) return;

    const lines = input.split("\n").filter((l) => l.trim().length > 0);
    if (lines.length === 0) return;

    setLoading(true);
    setResult("");

    setTimeout(() => {
      setResult(MOCK_RESPONSE);
      setLoading(false);
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b border-border px-6 py-5">
        <div className="mx-auto flex max-w-4xl items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/15">
            <User className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h1 className="text-lg font-semibold tracking-tight">
              LinkedIn Persona Dashboard
            </h1>
            <p className="text-sm text-muted-foreground">
              Powered by Gemini 2.5 Flash
            </p>
          </div>
        </div>
      </header>

      {/* Main */}
      <main className="mx-auto max-w-4xl px-6 py-10 space-y-8">
        {/* Input Section */}
        <section className="space-y-3">
          <label className="text-sm font-medium text-muted-foreground uppercase tracking-wider">
            LinkedIn Profile Data
          </label>
          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Paste the LinkedIn profile content here…"
            className="min-h-[200px] resize-y bg-card border-border text-foreground placeholder:text-muted-foreground focus-visible:ring-primary"
          />
          <Button
            onClick={handleGenerate}
            disabled={loading || !input.trim()}
            className="gap-2"
          >
            {loading ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
            {loading ? "Generating…" : "Generate Persona"}
          </Button>
        </section>

        {/* Output Section */}
        {result && (
          <section className="rounded-xl border border-border bg-card p-6 md:p-8 animate-in fade-in-0 slide-in-from-bottom-4 duration-500">
            <div className="prose prose-invert max-w-none prose-headings:text-foreground prose-p:text-secondary-foreground prose-strong:text-foreground prose-li:text-secondary-foreground">
              {result.split("\n").map((line, i) => {
                if (line.startsWith("# "))
                  return (
                    <h1 key={i} className="text-2xl font-bold mb-4">
                      {line.slice(2)}
                    </h1>
                  );
                if (line.startsWith("## "))
                  return (
                    <h2
                      key={i}
                      className="text-lg font-semibold mt-6 mb-2 text-primary"
                    >
                      {line.slice(3)}
                    </h2>
                  );
                if (line.startsWith("---"))
                  return <hr key={i} className="border-border my-4" />;
                if (line.startsWith("- "))
                  return (
                    <li key={i} className="ml-4 text-secondary-foreground">
                      {renderInline(line.slice(2))}
                    </li>
                  );
                if (/^\d+\.\s/.test(line))
                  return (
                    <li
                      key={i}
                      className="ml-4 list-decimal text-secondary-foreground"
                    >
                      {renderInline(line.replace(/^\d+\.\s/, ""))}
                    </li>
                  );
                if (line.startsWith("*") && line.endsWith("*"))
                  return (
                    <p key={i} className="text-sm italic text-muted-foreground mt-4">
                      {line.replace(/^\*|\*$/g, "")}
                    </p>
                  );
                if (line.trim() === "") return <br key={i} />;
                return (
                  <p key={i} className="text-secondary-foreground">
                    {renderInline(line)}
                  </p>
                );
              })}
            </div>
          </section>
        )}
      </main>
    </div>
  );
};

function renderInline(text: string) {
  const parts = text.split(/(\*\*[^*]+\*\*|\🟢[^\—]*)/g);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**"))
      return (
        <strong key={i} className="text-foreground font-semibold">
          {part.slice(2, -2)}
        </strong>
      );
    return <span key={i}>{part}</span>;
  });
}

export default PersonaDashboard;
